const BOOKS = {
	ADDED: 'BOOKS_ADDED',
	EDIT: 'BOOKS_EDIT',
	REMOVE: 'BOOKS_REMOVE',
}

const ALERT = {
	VISIBLE: 'ALERT_VISIBLE',
	HIDE: 'ALERT_HIDE',
}

const FORM = {
	CLEAR: 'FORM_CLEAR_BOOK',
	EDIT: 'FORM_EDIT_BOOK',
}

const SEARCH = 'SEARCH_BOOKS'

export { BOOKS, ALERT, FORM, SEARCH }
