const BOOKS = {
	INIT: '@@INIT',
	ADDED: 'BOOKS_ADDED',
	EDIT: 'BOOKS_EDIT',
	REMOVE: 'BOOKS_REMOVE',
}

const ALERT = {
	VISIBLE: 'ALERT_VISIBLE',
	HIDE: 'ALERT_HIDE',
	ALL_HIDE: 'ALL_ALERT_HIDE',
}

const SEARCH = 'SEARCH_BOOKS'

export { BOOKS, ALERT, SEARCH }
